from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QHBoxLayout,QVBoxLayout, QLineEdit, QRadioButton,QApplication, QWidget, QLabel, QPushButton
app = QApplication([])
my_win = QWidget()
my_win.setWindowTitle('«Десктопное приложение для проведения дифференциальнодиагностического опроса Е.А.Климова»')
my_win.move(1000, 500)
my_win.show() 
title = QLabel('Предположим, что после соответствующего обучения Вы можете выполнять любую работу. Но если бы Вам пришлось выбирать только из двух возможностей, какую бы Вы предпочли?')
v_line = QVBoxLayout()
h_line = QHBoxLayout()
v_line.addWidget(title, alignment = Qt.AlignTop)
my_win.setLayout(v_line)
radio_button_1 = QRadioButton('Ухаживать за животными')
radio_button_2 = QRadioButton('Обслуживать машины,приборы (следить,регулировать)')
button1 = QPushButton("Перейти к следующему вопросу")
v_line.addWidget(radio_button_1, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_2, alignment = Qt.AlignCenter)
v_line.addWidget(button1, alignment = Qt.AlignTop)
my_win.hide()
my_win.setWindowTitle('«Десктопное приложение для проведения дифференциальнодиагностического опроса Е.А.Климова»')
my_win.move(1000, 500)
my_win.show()
#def show_fun_title():
#   my_win.setWindowTitle('«Десктопное приложение для проведения дифференциальнодиагностического опроса Е.А.Климова»')
#   my_win.move(1000, 500)
#   my_win.show()
#button.clicked.connect(show_fun_title)

radio_button_3 = QRadioButton('Помогать больным людям,лечить их')
radio_button_4 = QRadioButton('Составлять таблицы, схемы, программы для вычислительных машин')
v_line.addWidget(radio_button_3, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_4, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_5 = QRadioButton('Следить за качеством книжных иллюстраций,плакатов, художественных открыток, грампластинок')
radio_button_6 = QRadioButton('Следить за состоянием, развитием растений')
v_line.addWidget(radio_button_5, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_6, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_7 = QRadioButton('Обрабатывать материалы (дерево, ткань, металл, пластмассу и т. п.)')
radio_button_8 = QRadioButton('Доводить товары до потребителя (рекомендовать, продавать)Обслуживать машины,приборы (следить,регулировать)')
v_line.addWidget(radio_button_7, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_8, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_9 = QRadioButton('Обсуждать научнопопулярные книги, статьи')
radio_button_10 = QRadioButton('Обсуждать художественные книги (пьесы, концерты)')
v_line.addWidget(radio_button_9, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_10, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_11 = QRadioButton('Выращивать молодняк(животных какой-либо породы)')
radio_button_12 = QRadioButton('Тренировать ровесников (или младших) в выполнении каких-либо действий (трудовых, учебных, спортивных)')
v_line.addWidget(radio_button_11, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_12, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_13 = QRadioButton('Копировать рисунки, изображения (или настраивать музыкальные инструменты)')
radio_button_14 = QRadioButton('Управлять каким-либо грузовым (подъемным или транспортным) средством')
v_line.addWidget(radio_button_13, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_14, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_15 = QRadioButton('Ремонтировать вещи, изделия (одежду, технику), жилище')
radio_button_16 = QRadioButton('Искать и исправлять ошибки в текстах, таблицах, рисунках')
v_line.addWidget(radio_button_15, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_16, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_17 = QRadioButton('Лечить животных')
radio_button_18 = QRadioButton('Выполнять вычисления, расчеты')
v_line.addWidget(radio_button_17, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_18, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_19 = QRadioButton('Выводить новые сорта растений')
radio_button_20 = QRadioButton('Конструировать, проектировать новые виды промышленных изделий (машины, одежду, дома, продукты питания и т. п.)')
v_line.addWidget(radio_button_19, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_20, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_23 = QRadioButton('Разбирать споры, ссоры между людьми, убеждать, разъяснять, наказывать, поощрять')
radio_button_24 = QRadioButton('Разбираться в чертежах, схемах, таблицах (проверять, уточнять и т. п.)')
v_line.addWidget(radio_button_23, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_24, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_25 = QRadioButton('Наблюдать, изучать работу кружков художественной самодеятельности')
radio_button_26 = QRadioButton('Наблюдать, изучать жизнь микробов')
v_line.addWidget(radio_button_25, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_26, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_27 = QRadioButton('Обслуживать, налаживать медицинские приборы,аппараты')
radio_button_28 = QRadioButton('Оказывать людям медицинскую помощь при ранениях, ушибах, ожогах и т. п')
v_line.addWidget(radio_button_27, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_28, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_29 = QRadioButton('Составлять точные описания или отчеты о наблюдаемых явлениях, событиях, измеряемых объектах и др.')
radio_button_30 = QRadioButton('Художественно описывать, изображать события (наблюдаемые или представляемые)')
v_line.addWidget(radio_button_29, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_30, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_31 = QRadioButton('Делать лабораторные анализы в больнице')
radio_button_32 = QRadioButton('Принимать, осматривать больных, беседовать с ними, назначать лечение')
v_line.addWidget(radio_button_31, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_32, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_33 = QRadioButton('Красить или расписывать помещение, поверхность изделий')
radio_button_34 = QRadioButton('Осуществлять монтаж зданий или сборку машин, приборов')
v_line.addWidget(radio_button_33, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_34, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_35 = QRadioButton('Организовывать культпоходы сверстников или младших (экскурсии, туристические походы и т. п.)')
radio_button_36 = QRadioButton('Играть на сцене, принимать участие в концертах')
v_line.addWidget(radio_button_35, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_36, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_37 = QRadioButton('Изготовлять по чертежам детали, изделия (машины, одежду), строить здания')
radio_button_38 = QRadioButton('Заниматься черчением, копировать чертежи, карты')
v_line.addWidget(radio_button_37, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_38, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
radio_button_39 = QRadioButton('Вести борьбу с болезнями растений, с вредителями леса, сада')
radio_button_40 = QRadioButton('Работать на клавишных машинах (пишущей машинке, телетайпе, ЭВМ и др.)')
v_line.addWidget(radio_button_39, alignment = Qt.AlignCenter)
v_line.addWidget(radio_button_40, alignment = Qt.AlignCenter)
my_win.hide()
my_win.show()
app.exec_()